#!/usr/bin/env groovy
@Library('devops-jenkins-ci@main') _
pipeline {

    agent any

    options {
        disableConcurrentBuilds()
        disableResume()
        timeout(time: 1, unit: 'HOURS')
    }
    
    stages {
        stage ('Load Pipeline') {
            when {
                allOf {
                    // Condition Check
                    anyOf{
                        // Branch Event: Nornal Flow
                        anyOf {
                            branch 'main'
                            branch 'jenkins'
                            branch 'PR-*'
                        }
                        // Manual Run: Only if checked.
                        allOf{
                            triggeredBy 'UserIdCause'
                        }
                    }
                }
            }
            steps {
                script {
                    nodejs('backend')
                }
            }
        }
    }

    post {
        cleanup {
            cleanWs()
        }
    }
}